server:
  host_port: "8080"
  health_port: "8081"
  cors:
    origins:
      - "http://localhost:3000"

tables:
  table_count: 10
  table_capacity: 8

database:
  host: "localhost"
  port: "9020"
  username: "influencer_social"

  #Shouldn't be in here, but just for this app
  password: "wowokwow"

  database: "influencer"
  driver: "mysql"
  timeout: "30"

  ssl_mode: "disable"
  max_idle_conns: 2
  max_open_conns: 5
  max_conn_life_time_minute: 30

routes:
  getGuestListUri: "/guest_list"
  postGuestListUri: "/guest_list/{name}"
  deleteGuestListUri: "/guest_list/{name}"

  getInvitationUri: "/invitation/{name}"

  getGuestsUri: "/guests"
  putGuestsUri: "/guests/{name}"
  deleteGuestsUri: "/guests/{name}"

  countEmptySeatsUri: "/seats_empty"
